services:
  web:
    build:
      context: .
    command: "bin/dev"
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: postgres:17.0
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=turbo_demo_development
      - TZ=Asia/Tokyo
volumes:
  db-data:
